name: Sauce

on:
  push:
    branches:
      - main
  pull_request:
    # This is the default list, but I don't know how to YAML an empty pull_request:
    types: [opened, reopened, synchronize]

jobs:
  tests-sauce:
    # Sauce tests need access to secrets.
    # Run only if PR's head repo is the same as base repo (lit/lit).
    # i.e. skip job if head repo is a fork.
    if: github.event.pull_request.head.repo.id == github.event.pull_request.base.repo.id

    # Sauce tests are still unreliable. Run them, but don't mark a commit as
    # failing if it fails.
    continue-on-error: true

    runs-on: ubuntu-latest
    env:
      BROWSERS: preset:sauce
      WIREIT_LOGGER: quiet-ci

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - uses: google/wireit@setup-github-actions-caching/v1

      - name: NPM install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: |
          cd packages/tests
          npm run test

      - name: Test SSR
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          # Sauce does not like multiple instances to be launched simultaneously
          WIREIT_PARALLEL: 1
        run: |
          cd packages/labs/ssr
          npm run test:integration
