name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    # This is the default list, but I don't know how to YAML an empty pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    # When lit-robot creates a release PR, skip this check as it will always
    # fail.
    if: ${{ github.actor != 'lit-robot' }}
    env:
      WIREIT_LOGGER: quiet-ci

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: NPM install
        run: |
          git checkout main
          git checkout ${{ github.sha }}
          npm ci

      - name: Lint
        run: npm run lint

      - name: Check formatting
        run: npm run format:check

      - name: Changeset
        # Enforce that all PRs that change packages need changesets. Changes
        # without changesets result in this job failing.
        run: npm run changeset status -- --since=main

  tests-local:
    runs-on: ubuntu-latest
    env:
      WIREIT_LOGGER: quiet-ci
      WIREIT_PARALLEL: 1

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # - uses: google/wireit@setup-github-actions-caching/v1

      - name: Install playwright deps
        run: npx playwright install-deps

      - name: NPM install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        env:
          BROWSERS: preset:local
          CONCURRENT_BROWSERS: 3
        run: npm run test

  windows-tools:
    runs-on: windows-latest
    env:
      WIREIT_LOGGER: quiet-ci

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # - uses: google/wireit@setup-github-actions-caching/v1

      - name: NPM install
        run: npm ci

      - name: Test
        env:
          RUN_BROWSER_TESTS: false
        run: npm run test:windows
